<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: http | William John Bert]]></title>
  <link href="http://williamjohnbert.com/categories/http/atom.xml" rel="self"/>
  <link href="http://williamjohnbert.com/"/>
  <updated>2014-06-01T17:21:13-04:00</updated>
  <id>http://williamjohnbert.com/</id>
  <author>
    <name><![CDATA[William John Bert]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[How legit HTTP (with an async io assist) massacred my Node workers]]></title>
    <link href="http://williamjohnbert.com/2013/09/why-chrome-sometimes-sends-the-same-post-multiple-times/"/>
    <updated>2013-09-10T18:55:00-04:00</updated>
    <id>http://williamjohnbert.com/2013/09/why-chrome-sometimes-sends-the-same-post-multiple-times</id>
    <content type="html"><![CDATA[<p>An uncaught exception in our Node app was causing not only one, but two and then
three workers to die. (Fortunately, we hardly ever encounter uncaught
exceptions. Really, just this one since launch a few months ago. We're Node
studs! Right?)</p>

<p>The funny thing is that we're using Express, which (via Connect) wraps each
request / response in a try / catch. And we use Express's error handler, which
returns 500 on unhandled errors.</p>

<p>Another funny thing is we use cluster, which isolates workers from each other.
They live in separate, solipsistic processes.</p>

<p>But instead of returning 500, our worker simply died. And, as if in sympathy,
the rest immediately followed.</p>

<p>Time to get to the bottom of this. A Node stud like me can figure it out. No
sweat. Right?</p>

<p>For a sanity check, I went to Chrome and Firefox's network inspectors. Only one
POST, the bad request that triggered the exception. Everything else looks
normal. Sanity: verified.</p>

<p>Then it was on to the
<a href="http://nodejs.org/docs/latest/api/cluster.html#cluster_how_it_works">cluster module</a>.
That magical "OS load balancing" seemed highly suspicious. But nope, I asked in
#nodejs and they said that only applies at the TCP connection level. Once a
connection is assigned to a worker, it never goes to another worker. Meaning
that the bad request was isolated&mdash;only the worker who received the initial
connection could encounter it.</p>

<p>But the workers kept on dying.</p>

<p>These workers morted out fast. They didn't even return 500, or any kind of
response. The more I thought about it, that didn't really seem right. Not right
at all. Why no 500?</p>

<p>But I can only tackle one mystery at a time. I wanted to understand: why did so
many workers die?</p>

<p>Furious googling ensued. My efforts were rewarded with this nugget:</p>

<blockquote><p>If an HTTP/1.1 client sends a request which includes a request body, but which
does not include an Expect request-header field with the “100-continue”
expectation, and if the client is not directly connected to an HTTP/1.1 origin
server, and if the client sees the connection close before receiving any status
from the server, the client SHOULD retry the request.</p></blockquote>

<p><small>(From the
<a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.2.4">HTTP 1.1 spec, RFC 2616</a>.
<a href="http://stackoverflow.com/a/14345476/599258">Original hat tip</a>, which links to
this
<a href="http://geek.starbean.net/?p=393">informative post about double HTTP requests</a>.)</small></p>

<p>My mind was somewhat blown. The browers were right after all. They were just
following HTTP. And&mdash;helpfully!&mdash;hiding the resent POSTs from the network
inspector.</p>

<p>But POSTs are dangerous. They mutate resources! I must only click the <em>Order</em>
button once or I may get charged multiple times!</p>

<p>I had a thought. One I have often, yet each time, it seems new again: <em>I have
much to learn</em>.</p>

<p>Back to the 500s. Or lack thereof. Which got funnier still when I realized that
other errors in our controllers that threw exceptions <em>did</em> return 500s. Being a
hands-on kind of guy, I added one right at the top of a route controller: <code>throw
new Error("uh-oh")</code>. My dev server spat back: <code>500 Error: uh-oh</code>.</p>

<p>So why did that one particular error never, ever return a 500, or any response
of any kind?</p>

<p>It's my fault, really. I'm still a Node newbie (I must never forget this). I had
missed that because async IO callbacks occur in a different call stack from the
request / response cyle, one that originates from the event loop,
<a href="http://stackoverflow.com/questions/13228649/unable-to-handle-exception-with-node-js-domains-using-express/13240256#13240256">Express's try / catch doesn't catch them</a>.</p>

<p>It makes total sense. I have much to learn.</p>

<p>So what to do? <code>require('domain')</code> to the rescue. I can write some middleware (a
bit of <a href="https://github.com/brianc/node-domain-middleware">this</a>, a dash of
<a href="https://github.com/mathrawka/express-domain-errors">that</a>) to wrap the request
/ response in a domain.</p>

<p>But how do I get this domain into my controller? My solution was to attach it to
<code>res.locals._domain</code>. Good solution? I don't know. I suspect there's a better
way. Good enough? It solved my immediate problem:</p>

<p><code>js
Model.find({key: value}, res.locals._domain.bind(function(err, docs) {
  // This callback can throw all it wants. My domain will catch it.
}));
</code></p>

<p>Sweet. Now, armed with a reference to <code>res</code> in the domain error handler, I can
return a 500. Voila, the browser gets its response. No more helpful resent
POSTs. The silent gratitude of the spared workers is its own reward.</p>

<p>Except, do I need to bind every
<a href="https://github.com/LearnBoost/mongoose/pull/1337">mongoose</a> and
<a href="https://github.com/joyent/node/issues/3908">other kind of async IO operation</a>
in my app? There are many.</p>

<p>Many.</p>

<p>I have much to learn.</p>
]]></content>
  </entry>
  
</feed>
